### ISSUE TITLE
OUT_OF_ENERGY

### ISSUE THREAD

**Issue by yanwankun** [tronprotocol/tron-contracts#11]
I want to deploy this TRC20 contract on the shasta test network, but I have been reporting "OUT_OF_ENERGY", I have frozen enough cpu and network, this is my account information

``````
Account information
  - Address: TKBNs9qR5iC4sprrZ5SWJUFxdCvFKF4sHU
  - Account:
  {
    "address": "4165065b7df967d64d208d802b3364b1d9992efcd5",
    "balance": 9989999000,
    "frozen": [
      {
        "frozen_balance": 20000000000,
        "expire_time": 1550309379000
      }
    ],
    "net_usage": 34398,
    "create_time": 1550039406000,
    "latest_opration_time": 1550460252000,
    "latest_consume_time": 1550460252000,
    "latest_consume_free_time": 1550050038000,
    "account_resource": {
      "energy_usage": 3478992,
      "frozen_balance_for_energy": {
        "frozen_balance": 660000000000,
        "expire_time": 1550719428000
      },
      "latest_consume_time_for_energy": 1550460252000
    }
  }

``````

I understand that the network has a limit on the length of the smart contract code. Can you give some advice?

**Comment by kidnapsteal** [comment]
@yanwankun  you might need to increase the `fee_limit` on the `tronbox.js`, it means that the fee requires to the network is too low

**Comment by yanwankun** [comment]
I learned from other places that this may be a bug in testing the network, and it seems that it is OK to not collateralize resources.
